### ISSUE TITLE
[Feature Request] Dark Mode

### ISSUE THREAD

**Issue by misspent** [sergiokas/Extensity#78]
Dark mode option in the settings would be nice.

**Example** - Coloured icons is personal preference, I did this because I'm a freak :)
![Dark Mode](https://i.imgur.com/65sm55B.gif)

<details>
  <summary align="center">CSS Code that made the example above possible</summary>
  <br>

```css
* { /* Makes everything sqaure */
	border-radius: 0px !important;
}
body {
    background-color: #151515 !important;
}

/* Search input text colour */
section#search input {
    color: #ccc !important;
}

/* Switch icon at the top */
.fa-toggle-on:before {
    color: crimson !important; /* Makes it green because of the invert(1) */
}
.fa-toggle-off:before {
    color: cyan !important;
}

/* Header */
section#header a#title {
    color: #4a74b5;
}
section#header {
    vertical-align: middle !important;
    margin-top: -5px !important;
    margin-bottom: 3px !important;
    background: #202020 !important;
}
section#header a.page[href="options.html"],
section#header a.page[href="profiles.html"],
section#header a.page[href="chrome://extensions"],
section#header a.switch {
    filter: invert(1) !important;
}
.fa-twitter:before {
    filter: brightness(1.1) !important;
}
.fa-facebook-official:before {
    filter: brightness(1.5) !important;
}
section#content h1 { /* Extensions "group" colour (I think) */
    background-color: #4d668b !important;
    background-image: -webkit-linear-gradient(top,#4d668b,#2b3e5c) !important;
}

/* Main section */
section#content ul li {
    color: #ccc !important;
    padding: 3px 2px !important;
    cursor: pointer !important;
}
section#content ul li:hover {
    color: cornflowerblue !important;
    text-shadow: none !important;
    background-color: #252525 !important;
    box-shadow: none !important;
}
section#content li.disabled {
    background-color: #410d0d !important;
    color: #ccc !important;
    opacity: .7 !important;
}
section#content li.disabled:hover {
	background-color: #410d0d !important;
}
/* Settings icons to the right of extension */
.fa-gear:before {
    color: #d67a0a;
}
```

</details>
